services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sns,sqs
      - DEBUG=${DEBUG:-0}
    volumes:
      - "./localstack-volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
